spring:
    kafka:
        producer:
            bootstrap-servers: 127.0.0.1:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: com.kafka.project.producer.KafkaProducerProject.KafkaNode.NodeSerializer
    application:
        name: kafka producer

server:
    port: 8081